import mongoose from "mongoose";

const rfiSchema = new mongoose.Schema(
  {
    question: { type: String, required: true },
    answer: { type: String },
    citedChunks: [
      {
        document: { type: mongoose.Schema.Types.ObjectId, ref: "Document" },
        chunkIndex: Number,
        excerpt: String,
      },
    ],
    status: { type: String, enum: ["open", "answered", "duplicate_resolved"], default: "open" },
    similarPastRFIs: [{ type: mongoose.Schema.Types.ObjectId, ref: "RFI" }],
    autoGeneratedFrom: {
      // traceability: was this RFI born from a compliance deviation?
      sourceType: { type: String, enum: ["manual", "compliance_deviation", "schedule_risk"] },
      sourceRef: mongoose.Schema.Types.ObjectId,
    },
    raisedBy: { type: String, default: "Field Engineer" },
  },
  { timestamps: true }
);

export default mongoose.model("RFI", rfiSchema);
