import Document from "../models/Document.js";
import ComplianceCheck from "../models/ComplianceCheck.js";
import RFI from "../models/RFI.js";
import { retrieveRelevantChunks, formatChunksForPrompt } from "./rag/ragService.js";
import { askLLMForJSON } from "./aiClient.js";
import { logAgentAction } from "./auditService.js";

const SYSTEM_PROMPT = `You are a Specification & Quality Compliance Agent for a hyperscale data centre EPC project.
Compare the SUBMITTAL against the retrieved SPECIFICATION clauses.
If NO specification clauses are retrieved, you MUST still evaluate the SUBMITTAL for general EPC industry best practices, missing standard parameters (e.g. dimensions, testing parameters), and completeness.
Be precise and conservative: only flag a deviation when the submittal text genuinely
contradicts, falls short of, or omits a spec requirement or basic industry standard. Cite the exact clause reference when available. 
Respond ONLY with strict JSON, no prose, no markdown fences, matching:
{
  "verdict": "compliant" | "deviation" | "needs_review",
  "confidence": number (0-100),
  "findings": [
    { "clause": string, "specText": string, "submittalText": string, "issue": string, "severity": "low"|"medium"|"high"|"critical" }
  ],
  "summary": string
}`;

export async function runComplianceCheck({ submittalDocumentId, system }) {
  const submittal = await Document.findById(submittalDocumentId);
  if (!submittal) throw new Error("Submittal document not found");

  // Retrieve the most relevant SPEC clauses for this submittal's own text -
  // this is the shared RAG index doing double duty.
  const relevantSpecChunks = await retrieveRelevantChunks({
    query: submittal.rawText.slice(0, 2000),
    documentType: "specification",
    system: system || submittal.system,
    topK: 8,
  });

  const context = formatChunksForPrompt(relevantSpecChunks);

  const prompt = `SPECIFICATION CLAUSES RETRIEVED:\n${context || "(no matching spec clauses found)"}\n\nSUBMITTAL DOCUMENT ("${submittal.title}"):\n${submittal.rawText.slice(0, 4000)}\n\nEvaluate compliance.`;

  const result = await askLLMForJSON({ system: SYSTEM_PROMPT, prompt, maxTokens: 1500 });

  const check = await ComplianceCheck.create({
    submittalDocument: submittal._id,
    specDocument: relevantSpecChunks[0]?.document?._id,
    system: system || submittal.system,
    verdict: result.verdict,
    confidence: result.confidence,
    findings: result.findings || [],
    summary: result.summary,
  });

  await logAgentAction({
    agent: "compliance_agent",
    action: `verdict_${result.verdict}`,
    entityType: "ComplianceCheck",
    entityId: check._id,
    evidence: relevantSpecChunks.map((c) => `${c.document?.title} ${c.clauseRef || ""}`.trim()),
    reasoning: result.summary,
    outcome: result.verdict,
  });

  // Closed loop: a deviation auto-drafts an RFI instead of just sitting in a report.
  if (result.verdict === "deviation") {
    const rfi = await RFI.create({
      question: `Deviation identified in "${submittal.title}": ${result.findings?.[0]?.issue || result.summary}. Please confirm required corrective action.`,
      status: "open",
      autoGeneratedFrom: { sourceType: "compliance_deviation", sourceRef: check._id },
      raisedBy: "AI Compliance Agent",
    });
    check.linkedRFI = rfi._id;
    await check.save();
  }

  return check;
}

export async function listComplianceChecks(filter = {}) {
  return ComplianceCheck.find(filter)
    .populate("submittalDocument", "title vendor system")
    .populate("specDocument", "title")
    .populate("linkedRFI")
    .sort({ createdAt: -1 });
}
