import { useEffect, useState } from "react";
import { RFIAPI } from "../services/api.js";
import TitleBlock from "../components/TitleBlock.jsx";
import { Loader, EmptyState, Panel } from "../components/ui.jsx";
import { Send } from "lucide-react";

export default function RFICopilot() {
  const [rfis, setRfis] = useState(null);
  const [question, setQuestion] = useState("");
  const [asking, setAsking] = useState(false);
  const [error, setError] = useState(null);

  const load = () => { RFIAPI.list().then(setRfis); };
  useEffect(load, []);

  const ask = async () => {
    if (!question.trim()) return;
    setAsking(true);
    setError(null);
    try {
      await RFIAPI.ask(question);
      setQuestion("");
      load();
    } catch (e) {
      setError(e.response?.data?.error || e.message);
    } finally {
      setAsking(false);
    }
  };

  return (
    <div>
      <TitleBlock
        sheet="DWG-05"
        title="Project Knowledge & RFI Intelligence Copilot"
        subtitle="RAG over specs, submittals, RFIs, and change orders — cited answers, with duplicate-RFI detection"
        meta={{ label: "Logged RFIs", value: rfis?.length ?? "—" }}
      />

      <Panel className="p-5 mb-6">
        <div className="flex gap-3">
          <input
            value={question}
            onChange={(e) => setQuestion(e.target.value)}
            onKeyDown={(e) => e.key === "Enter" && ask()}
            placeholder="Ask a technical or contractual question about the project documents..."
            className="flex-1 bg-blueprint-panel2 border border-blueprint-line text-sm text-ink-primary px-3 py-2 rounded font-mono placeholder:text-ink-faint"
          />
          <button
            onClick={ask}
            disabled={asking || !question.trim()}
            className="flex items-center gap-2 bg-signal-cyan/10 border border-signal-cyan text-signal-cyan px-4 py-2 rounded text-sm font-mono hover:bg-signal-cyan/20 disabled:opacity-40 transition-colors"
          >
            <Send size={15} />
            {asking ? "Retrieving..." : "Ask"}
          </button>
        </div>
        {error && <p className="text-signal-rose text-xs mt-2">{error}</p>}
      </Panel>

      {!rfis && <Loader label="Loading RFI log" />}
      {rfis && rfis.length === 0 && <EmptyState message="No RFIs yet. Ask a question above, or run a compliance check to auto-generate one." />}

      <div className="space-y-4">
        {rfis?.map((r) => (
          <Panel key={r._id} className="p-5">
            <p className="text-sm text-ink-primary font-medium mb-1">{r.question}</p>
            <span className="text-[10px] font-mono text-ink-faint uppercase">
              {r.autoGeneratedFrom?.sourceType === "compliance_deviation" ? "Auto-generated from compliance deviation" : r.raisedBy}
            </span>
            {r.answer && <p className="text-sm text-ink-muted mt-3 whitespace-pre-wrap">{r.answer}</p>}

            {r.citedChunks?.length > 0 && (
              <div className="mt-3 border-t border-blueprint-line pt-2 space-y-1">
                {r.citedChunks.map((c, i) => (
                  <p key={i} className="text-[10px] font-mono text-signal-cyan">
                    [Source {i + 1}] {c.document?.title}
                  </p>
                ))}
              </div>
            )}

            {r.similarPastRFIs?.length > 0 && (
              <p className="text-[11px] text-signal-amber mt-2 font-mono">
                ⟳ {r.similarPastRFIs.length} similar past RFI(s) found — potential rework reduction
              </p>
            )}
          </Panel>
        ))}
      </div>
    </div>
  );
}
